config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index
  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def contacts
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Web</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.haml
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/contacts.html.haml
<h1>Main#contacts</h1>
<p>Find me in app/views/main/contacts.html.erb</p>

app/views/main/help.html.haml
<h1>Main#help</h1>
<p>Find me in app/views/main/help.html.erb</p>

app/views/main/index.html.haml
%h1 Main page
%ul
        %li= link_to 'Contacts', main_contacts_path
        %li= link_to 'Help', main_help_path
        %li= link_to 'About', main_about_path
        %li= link_to 'Ruby on Rails Website', 'http://rubyonrails.org'